### PR TITLE
GDEV-72 - FastAPI boilerplate

### PR DESCRIPTION
**Pull request by KerstenBreuer**
Please have a look at the example on how to use it:  
https://github.com/ghga-de/ghga-service-chassis-lib/tree/feature/rest/examples

This PR also includes changes from #2. You might such review #2 first.

### CODE REVIEW

**Review by deepakunni3 — COMMENTED** [review]
The PR looks good, but I had some issues while running tests. Are you seeing the same @KerstenBreuer ?

```sh
collected 7 items                                                                                                                              

tests/unit/test_api.py F                                                                                                                 [ 14%]
tests/unit/test_config.py ......                                                                                                         [100%]

=================================================================== FAILURES ===================================================================
_______________________________________________________________ test_run_server ________________________________________________________________

    def test_run_server():
        """Test the run_server wrapper function"""
        config = ApiConfigBase()
        config.port = find_free_port()
    
        process = multiprocessing.Process(
            target=run_server, kwargs={"app": app, "config": config}
        )
>       process.start()

tests/unit/test_api.py:34: 
...
obj = <Process name='Process-1' parent=79498 initial>, file = <_io.BytesIO object at 0x7fb38ed7ba90>, protocol = None

    def dump(obj, file, protocol=None):
        '''Replacement for pickle.dump() using ForkingPickler.'''
>       ForkingPickler(file, protocol).dump(obj)
E       AttributeError: Can't pickle local object 'FastAPI.setup.<locals>.openapi'

/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/multiprocessing/reduction.py:60: AttributeError
```

**Comment by KerstenBreuer** [comment]
Hi @deepakunni3, thanks for testing it. No I am not getting that error nor does the CI (which is also running these tests).

How are you running the tests? Are you using the devcontainer?

**Review by alamgirmani — APPROVED** [review]

**Comment by alamgirmani** [comment]
@KerstenBreuer can you please resolve the conflicts so that we can merge this branch?

**Comment by KerstenBreuer** [comment]
@alamgirmani, thanks for the reminder. The merge conflicts were fixed. Let's wait for @deepakunni3 to follow up on the error he reported and then we can merge it.

**Comment by deepakunni3** [comment]
Yes, can confirm that the errors are not there when running in a dev container

**Review by deepakunni3 — APPROVED** [review]

**Review by ac-jorellanaf — APPROVED** [review]

**Pull request merged**
